name: Linux VNC Servep

on:
  workflow_dispatch:

jobs:
  linux_vnc_serveo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y xvfb x11vnc wget curl jq default-jre unzip python3-pip xfce4 xfce4-goodies openssh-client

      - name: Install Google Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb || sudo apt -f install -y

      - name: Verify Google Chrome installation
        run: google-chrome --version

      - name: Set up Xvfb, Xfce, and VNC
        run: |
          # Start Xvfb (creates a virtual display)
          Xvfb :1 -screen 0 1024x768x16 &
          export DISPLAY=:1
          echo "export DISPLAY=:1" >> $GITHUB_ENV
          sleep 2

          # Start the Xfce desktop environment
          startxfce4 &
          sleep 5

          # Set up and start the VNC server using x11vnc
          x11vnc -storepasswd ${{ secrets.VNC_PASSWORD }} /tmp/passwd
          x11vnc -forever -rfbauth /tmp/passwd -display :1 -shared -bg
          sleep 1

      - name: Generate random port for this run
        id: random-port
        run: |
          # Generate a random port number between 5900 and 6000 (to avoid overlap with default port)
          RANDOM_PORT=$((5900 + RANDOM % 100))
          echo "Random VNC port: $RANDOM_PORT"
          echo "VNC_PORT=$RANDOM_PORT" >> $GITHUB_ENV

      - name: Start Serveo tunnel with random port
        run: |
          # Use GITHUB_RUN_ID to generate a unique subdomain for the SSH tunnel
          SUBDOMAIN="vnc-${GITHUB_RUN_ID}"
          VNC_PORT=$VNC_PORT
          echo "Using custom subdomain: $SUBDOMAIN on port: $VNC_PORT"
          
          # Start the Serveo tunnel with our custom subdomain and random VNC port
          # Forward VNC on port $VNC_PORT to the subdomain ${SUBDOMAIN}.serveo.net
          ssh -o StrictHostKeyChecking=no -R ${SUBDOMAIN}:${VNC_PORT}:localhost:${VNC_PORT} serveo.net > serveo.log 2>&1 &
          sleep 5

      - name: Display Serveo public VNC address
        run: |
          echo "⏳ Detecting Serveo public address..."
          SUBDOMAIN="vnc-${GITHUB_RUN_ID}"
          VNC_PORT=$VNC_PORT
          VNC_ADDRESS="${SUBDOMAIN}.serveo.net:${VNC_PORT}"
          
          # Optionally, verify this in the serveo log (if you’d like to check the log contents)
          cat serveo.log
          echo "✅ Public VNC address: $VNC_ADDRESS"
          echo "🔗 Use this address in your VNC client (e.g. RealVNC): $VNC_ADDRESS"

      - name: Confirm DISPLAY env
        run: echo $DISPLAY

      - name: Keep job alive (waiting for continue.txt)
        run: |
          echo "🔧 Session is active. Connect your VNC client to the address above."
          echo "Create a file named 'continue.txt' in the repository to proceed."
          while [ ! -f continue.txt ]; do
            sleep 10
          done
